### ISSUE TITLE
Setting to filter zoom meetings from displaying on the calendar

### ISSUE THREAD

**Issue by daviddecorso** [daviddecorso/InstaTask#57]
Ideally zoom meetings are identified in the parse function and a boolean is added to an event in the db to check whether it's a zoom meeting or not to make the frontend fast.

**Comment by lucasrossell** [comment]
In the webcourses ics import, the location parameter is set to "Zoom Online Meeting" for Zoom meetings. This could probably be used to pretty easily filter them out

**Comment by daviddecorso** [comment]
#83 filters the task cards. Calendar filtering still needs to be implemented.

**Comment by daviddecorso** [comment]
#95
