### ISSUE TITLE
Calendar view visual error in "week" section

### ISSUE THREAD

**Issue by lucasrossell** [daviddecorso/InstaTask#89]
![image](https://user-images.githubusercontent.com/66089826/110833170-2bec9000-826a-11eb-8cb7-bf823209b7e4.png)

**Comment by lucasrossell** [comment]
When multiple events are happening at the same time, the boxes get stacked/crowded in a weird way.

**Comment by daviddecorso** [comment]
This is expected behavior and not a bug. There's likely a way to change this, but I'm not sure what we'd change it to, as the week view seems to be generally problematic because of the lack of horizontal space. I think clicking/hovering an event to show more details would be a potential fix.
